M48
; DRILL file KiCad 10.0.1 date 2026-08-12T01:57:15
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-12T01:57:15+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X139.295Y-146.23
X140.995Y-146.23
T2
X138.52Y-129.15
X160.92Y-129.05
M30
